apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization                        
commonLabels:                              
  app: inventoryapp                               
resources:                                 
  - deployment.yaml                        
  - service.yaml                           
configMapGenerator:                        
  - name: inventoryapp-map                        
    literals:                              
      - KEY=value                          
