apiVersion: v1        
kind: Service         
metadata:             
  name: inventoryapp         
spec:                 
  selector:           
    app: inventoryapp        
  ports:              
    - port: 8086      
      targetPort: 8086
